### ISSUE TITLE
Update #10818 broke the layout of the Folksonomy properties panel

### ISSUE THREAD

**Issue by October-Food-Facts** [openfoodfacts/openfoodfacts-server#10860]
#10818 broke the layout of the Folksonomy properties panel. In the image put together, on top, it's shown how the layout used to be, while on the bottom it's how the layout is now, broken. The column headers were made misaligned with their content, so that "Value" now incorrectly corresponds to the "Enter a property" input field, while the input field of "Value" no longer has its column header on top.
![Image](https://github.com/user-attachments/assets/e7772817-db52-4858-b15e-cba549cd5b19)
Don't forget to check the layout for when properties are present and listed on the above panels. It's not possible to show if anything changed, as there aren't screenshots of how it used to be.

**Comment by Malay-dev** [comment]
Hey... Can I work on this issue?

**Comment by teolemon** [comment]
cc @CharlesNepote

**Comment by CharlesNepote** [comment]
Thanks, fixed via #10857 

![Image](https://github.com/user-attachments/assets/7bdb5c66-cc0a-4d0a-b894-5d3fcae079ec)

**Comment by October-Food-Facts** [comment]
This hasn't been fixed and should be reopened.
> Don't forget to check the layout for when properties are present

...and are newly added.

The issue is still present for properties that were just added, until the page is accessed again or reloaded.
