### ISSUE TITLE
Top translators not deployed correctly

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-server#1124]
Link on the footers to Translators is here, doesn't work:
https://world.openfoodfacts.org/cgi/top_translators.pl

**Comment by thezillion** [comment]
The file is present in the repository. Guess the file isn't present on the main server? Recloning should work.

**Comment by hangy** [comment]
404 on off.net:
- [ ] https://static.openfoodfacts.net/bower_components/osmtogeojson/osmtogeojson.js
- [ ] https://static.openfoodfacts.net/js/display-tag.js

**Comment by yarons** [comment]
404 is gone yet the table is unpopulated.

**Comment by VaiTon** [comment]
`Access to XMLHttpRequest at 'https://static.openfoodfacts.org/data/top_translators.csv' from origin 'https://world.openfoodfacts.org' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by VaiTon** [comment]
We should add the header `Access-Control-Allow-Origin` to the response

**Comment by hangy** [comment]
CORS issue has been fixed recently, see #2777

**Comment by yarons** [comment]
There's still an error message and I even found another bug on this page.
