### ISSUE TITLE
Brands name that are less than 4 characters long and compose by number only don't display from the brands drilldown url

### ISSUE THREAD

**Issue by kyzh** [openfoodfacts/openfoodfacts-server#34]
An example for working brand "1848": http://world.openfoodfacts.org/brand/1848
An example for a not working brand "365": http://world.openfoodfacts.org/brand/365 
See http://world.openfoodfacts.org/brands for a complete list.

**Comment by kyzh** [comment]
this is now possible for brand make of letters: eg. http://world.openfoodfacts.org/brand/u
Still not the case for numbers: eg. http://world.openfoodfacts.org/brand/365
It is even worse since the page is completly blank

**Comment by TaciteOFF** [comment]
Still doesn't work for numbers:

http://fr.openfoodfacts.org/marque/555

**Comment by stephanegigandet** [comment]
Fixed numbers.

**Comment by TaciteOFF** [comment]
Problem came back with OBF
http://fr.openbeautyfacts.org/produit/3700311811858/dissolvant
